/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "parser_2_tester.hpp"

using namespace roq;
using namespace roq::htx_futures;

using namespace std::literals;
using namespace std::chrono_literals;

using namespace Catch::literals;

using value_type = json::PositionsCross;

TEST_CASE("usdt_m_futures_init", "[json_positions_across]") {
  auto message = R"({)"
                 R"("op":"notify",)"
                 R"("topic":"positions_cross",)"
                 R"("ts":1764845989317,)"
                 R"("event":"init",)"
                 R"("data":[{)"
                 R"("contract_type":"swap",)"
                 R"("pair":"APT-USDT",)"
                 R"("business_type":"swap",)"
                 R"("liquidation_price":null,)"
                 R"("symbol":"APT",)"
                 R"("contract_code":"APT-USDT",)"
                 R"("volume":0,)"
                 R"("available":0,)"
                 R"("frozen":0,)"
                 R"("cost_open":0,)"
                 R"("cost_hold":0,)"
                 R"("profit_unreal":0,)"
                 R"("profit_rate":0,)"
                 R"("profit":0,)"
                 R"("margin_asset":"USDT",)"
                 R"("position_margin":0,)"
                 R"("lever_rate":1,)"
                 R"("direction":"buy",)"
                 R"("last_price":1.9963,)"
                 R"("margin_mode":"cross",)"
                 R"("margin_account":"USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("adl_risk_percent":null)"
                 R"(},{)"
                 R"("contract_type":"swap",)"
                 R"("pair":"APT-USDT",)"
                 R"("business_type":"swap",)"
                 R"("liquidation_price":null,)"
                 R"("symbol":"APT",)"
                 R"("contract_code":"APT-USDT",)"
                 R"("volume":0,)"
                 R"("available":0,)"
                 R"("frozen":0,)"
                 R"("cost_open":0,)"
                 R"("cost_hold":0,)"
                 R"("profit_unreal":0,)"
                 R"("profit_rate":0,)"
                 R"("profit":0,)"
                 R"("margin_asset":"USDT",)"
                 R"("position_margin":0,)"
                 R"("lever_rate":1,)"
                 R"("direction":"sell",)"
                 R"("last_price":1.9963,)"
                 R"("margin_mode":"cross",)"
                 R"("margin_account":"USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("adl_risk_percent":null)"
                 R"(},{)"
                 R"("contract_type":"swap",)"
                 R"("pair":"BTC-USDT",)"
                 R"("business_type":"swap",)"
                 R"("liquidation_price":null,)"
                 R"("symbol":"BTC",)"
                 R"("contract_code":"BTC-USDT",)"
                 R"("volume":0,)"
                 R"("available":0,)"
                 R"("frozen":0,)"
                 R"("cost_open":0,)"
                 R"("cost_hold":0,)"
                 R"("profit_unreal":0,)"
                 R"("profit_rate":0,)"
                 R"("profit":0,)"
                 R"("margin_asset":"USDT",)"
                 R"("position_margin":0,)"
                 R"("lever_rate":10,)"
                 R"("direction":"buy",)"
                 R"("last_price":93200,)"
                 R"("margin_mode":"cross",)"
                 R"("margin_account":"USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("adl_risk_percent":null)"
                 R"(},{)"
                 R"("contract_type":"swap",)"
                 R"("pair":"BTC-USDT",)"
                 R"("business_type":"swap",)"
                 R"("liquidation_price":null,)"
                 R"("symbol":"BTC",)"
                 R"("contract_code":"BTC-USDT",)"
                 R"("volume":0,)"
                 R"("available":0,)"
                 R"("frozen":0,)"
                 R"("cost_open":0,)"
                 R"("cost_hold":0,)"
                 R"("profit_unreal":0,)"
                 R"("profit_rate":0,)"
                 R"("profit":0,)"
                 R"("margin_asset":"USDT",)"
                 R"("position_margin":0,)"
                 R"("lever_rate":10,)"
                 R"("direction":"sell",)"
                 R"("last_price":93200,)"
                 R"("margin_mode":"cross",)"
                 R"("margin_account":"USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("adl_risk_percent":null)"
                 R"(})"
                 R"(],)"
                 R"("uid":"573242943")"
                 R"(})";
  auto helper = [](value_type const &obj) { CHECK(obj.op == json::Operator::NOTIFY); };
  Parser2Tester<value_type>::dispatch(helper, message, 8192, 1);
}
