/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/htx_futures/json/account_info.hpp"

using namespace roq;
using namespace roq::htx_futures;

using namespace std::literals;
using namespace std::chrono_literals;

using namespace Catch::literals;

// note! reduced
TEST_CASE("linear_swap_isolated", "[json_account_info]") {
  auto message = R"({)"
                 R"("status":"ok",)"
                 R"("data":[{)"
                 R"( "symbol":"BTC",)"
                 R"("margin_balance":0,)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":0,)"
                 R"("profit_unreal":0,)"
                 R"("risk_rate":null,)"
                 R"("new_risk_rate":null,)"
                 R"("withdraw_available":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.040000000000000000,)"
                 R"("margin_static":0,)"
                 R"("contract_code":"BTC-USDT",)"
                 R"("margin_asset":"USDT",)"
                 R"("margin_mode":"isolated",)"
                 R"("margin_account":"BTC-USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("positionList":[])"
                 R"(},{)"
                 R"("symbol":"ETH",)"
                 R"("margin_balance":0,)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":0,)"
                 R"("profit_unreal":0,)"
                 R"("risk_rate":null,)"
                 R"("new_risk_rate":null,)"
                 R"("withdraw_available":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.050000000000000000,)"
                 R"("margin_static":0,)"
                 R"("contract_code":"ETH-USDT",)"
                 R"("margin_asset":"USDT",)"
                 R"("margin_mode":"isolated",)"
                 R"("margin_account":"ETH-USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("positionList":[])"
                 R"(},{)"
                 R"("symbol":"GMT",)"
                 R"("margin_balance":0,)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":0,)"
                 R"("profit_unreal":0,)"
                 R"("risk_rate":null,)"
                 R"("new_risk_rate":null,)"
                 R"("withdraw_available":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.200000000000000000,)"
                 R"("margin_static":0,)"
                 R"("contract_code":"GMT-USDT",)"
                 R"("margin_asset":"USDT",)"
                 R"("margin_mode":"isolated",)"
                 R"("margin_account":"GMT-USDT",)"
                 R"("trade_partition":"USDT",)"
                 R"("position_mode":"dual_side",)"
                 R"("positionList":[])"
                 R"(})"
                 R"(],)"
                 R"("ts":1763206740448)"
                 R"(})";
  core::json::BufferStack buffer{8192, 2};
  [[maybe_unused]] json::AccountInfo obj{message, buffer};
}

// note! reduced
TEST_CASE("linear_swap_cross", "[json_account_info]") {
  auto message = R"({)"
                 R"("status":"ok",)"
                 R"("data":[{)"
                 R"("futures_contract_detail":[{)"
                 R"("symbol":"BTC",)"
                 R"("contract_code":"BTC-USDT-251128",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.075000000000000000,)"
                 R"("contract_type":"next_week",)"
                 R"("pair":"BTC-USDT",)"
                 R"("business_type":"futures",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(},{)"
                 R"("symbol":"BTC",)"
                 R"("contract_code":"BTC-USDT-251121",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.075000000000000000,)"
                 R"("contract_type":"this_week",)"
                 R"("pair":"BTC-USDT",)"
                 R"("business_type":"futures",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(},{)"
                 R"("symbol":"ETH",)"
                 R"("contract_code":"ETH-USDT-251128",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.150000000000000000,)"
                 R"("contract_type":"next_week",)"
                 R"("pair":"ETH-USDT",)"
                 R"("business_type":"futures",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(},{)"
                 R"("symbol":"ETH",)"
                 R"("contract_code":"ETH-USDT-251121",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.150000000000000000,)"
                 R"("contract_type":"this_week",)"
                 R"("pair":"ETH-USDT",)"
                 R"("business_type":"futures",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(})"
                 R"(],)"
                 R"("margin_mode":"cross",)"
                 R"("margin_account":"USDT",)"
                 R"("margin_asset":"USDT",)"
                 R"("margin_balance":100.78902708,)"
                 R"("money_in":100.78902708,)"
                 R"("money_out":0,)"
                 R"("margin_static":100.78902708,)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("profit_unreal":0,)"
                 R"("withdraw_available":100.78902708,)"
                 R"("risk_rate":null,)"
                 R"("new_risk_rate":0,)"
                 R"("contract_detail":[{)"
                 R"("symbol":"SATS",)"
                 R"("contract_code":"SATS-USDT",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.200000000000000000,)"
                 R"("contract_type":"swap",)"
                 R"("pair":"SATS-USDT",)"
                 R"("business_type":"swap",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(},{)"
                 R"("symbol":"OKB",)"
                 R"("contract_code":"OKB-USDT",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.200000000000000000,)"
                 R"("contract_type":"swap",)"
                 R"("pair":"OKB-USDT",)"
                 R"("business_type":"swap",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(},{)"
                 R"("symbol":"C",)"
                 R"("contract_code":"C-USDT",)"
                 R"("margin_position":0,)"
                 R"("margin_frozen":0,)"
                 R"("margin_available":100.789027080000000000,)"
                 R"("profit_unreal":0,)"
                 R"("liquidation_price":null,)"
                 R"("lever_rate":10,)"
                 R"("adjust_factor":0.200000000000000000,)"
                 R"("contract_type":"swap",)"
                 R"("pair":"C-USDT",)"
                 R"("business_type":"swap",)"
                 R"("trade_partition":"USDT",)"
                 R"("cross_max_available":0)"
                 R"(})"
                 R"(],)"
                 R"("position_mode":"dual_side",)"
                 R"("fixed_margin_position":null,)"
                 R"("margin_available":null)"
                 R"(})"
                 R"(],)"
                 R"("ts":1763206740772)"
                 R"(})";
  core::json::BufferStack buffer{8192, 2};
  [[maybe_unused]] json::AccountInfo obj{message, buffer};
}

